export const projects = [
  {
    logo: "/logo/pixelkitLogo.svg",
    width: 256,
    height: 256,
    title: "PixelKit",
    link: "/p/pixelkit",
  },
  {
    logo: "/logo/parserLogo.svg",
    width: 256,
    height: 256,
    title: "Parser GUI",
    link: "/p/parser",
  },
  {
    logo: "logo/snakeAILogo.png",
    width: 422,
    height: 422,
    title: "Snake AI",
    link: "/p/snake/",
  },
  {
    logo: "logo/gameOfLiveLogo.png",
    width: 500,
    height: 494,
    title: "Game of Live",
    link: "/p/gameOfLive",
  },
  {
    logo: "logo/hanoiLogo.png",
    width: 452,
    height: 430,
    title: "Towers of Hanoi",
    link: "/p/towers",
  },
  {
    logo: "logo/mobitvaLogo.png",
    width: 964,
    height: 868,
    title: "Мобитва next",
    link: "/p/mobilefight",
  },
  {
    logo: "logo/playerLogo.png",
    width: 1072,
    height: 1240,
    title: "Музыкальный плеер",
    link: "/p/player",
  },
  {
    logo: "/logo/engineLogo.svg",
    width: 256,
    height: 256,
    title: "PHP engine",
    link: "/p/engine",
  },
  {
    logo: "/logo/tasksSolutionsLogo.svg",
    width: 256,
    height: 256,
    title: "Tasks Solutions",
    link: "/p/tasks-solutions",
  },
];
