export const projects = [
  {
    logo: "/logo/irisLogo.png",
    width: 1024,
    height: 1024,
    title: "Iris",
    description: "Pro-камера с manual controls и native look-bake",
    link: "/p/iris",
  },
  {
    logo: "/logo/lenswireLogo.png",
    width: 1024,
    height: 1024,
    title: "Lenswire",
    description: "On-device HTTP(S) inspector с локальным MITM",
    link: "/p/lenswire",
  },
  {
    logo: "/logo/pixelkitLogo.svg",
    width: 256,
    height: 256,
    title: "PixelKit",
    description: "Фото-тулкит в браузере: фон, конвертация, сжатие",
    link: "/p/pixelkit",
  },
  {
    logo: "/logo/parserLogo.svg",
    width: 256,
    height: 256,
    title: "Parser GUI",
    description: "Генератор селекторов и кода для Puppeteer",
    link: "/p/parser",
  },
  {
    logo: "logo/snakeAILogo.png",
    width: 422,
    height: 422,
    title: "Snake AI",
    description: "Визуализация A*, BFS и DFS на игровом поле",
    link: "/p/snake/",
  },
  {
    logo: "logo/gameOfLiveLogo.png",
    width: 500,
    height: 494,
    title: "Game of Live",
    description: "Игра «Жизнь» на ReasonML / ReasonJS",
    link: "/p/gameOfLive",
  },
  {
    logo: "logo/hanoiLogo.png",
    width: 452,
    height: 430,
    title: "Towers of Hanoi",
    description: "Интерактивная демонстрация рекурсивного алгоритма",
    link: "/p/towers",
  },
  {
    logo: "logo/mobitvaLogo.png",
    width: 964,
    height: 868,
    title: "Мобитва next",
    description: "Квесты, чат и PvP в духе классической «Мобитвы»",
    link: "/p/mobilefight",
  },
  {
    logo: "logo/playerLogo.png",
    width: 1072,
    height: 1240,
    title: "Музыкальный плеер",
    description: "Плеер с аудиовизуализацией в реальном времени",
    link: "/p/player",
  },
  {
    logo: "/logo/engineLogo.svg",
    width: 256,
    height: 256,
    title: "PHP engine",
    description: "Учебный PHP-бэкенд с маршрутизацией и MVC",
    link: "/p/engine",
  },
  {
    logo: "/logo/tasksSolutionsLogo.svg",
    width: 256,
    height: 256,
    title: "Tasks Solutions",
    description: "Алгоритмы, паттерны и подготовка к собеседованиям",
    link: "/p/tasks-solutions",
  },
];
